[build]
  command = "pip install -r requirements.txt && python main.py build"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.12" 